### ISSUE TITLE
Unable to compile version 0.40.0

### ISSUE THREAD

**Issue by SonOfFlyingPig** [PistonDevelopers/piston_window#126]
When running `cargo build` on 0.40.0 I get the following:
```
   Compiling piston_window v0.40.0 (file:///home/mike/projects/piston_window)
src/lib.rs:78:9: 78:27 error: unresolved import `piston::window::*`. Could not find `window` in `piston` [E0432]
src/lib.rs:78 pub use piston::window::*;
                      ^~~~~~~~~~~~~~~~~~
src/lib.rs:78:9: 78:27 help: run `rustc --explain E0432` to see a detailed explanation
src/lib.rs:80:9: 80:31 error: unresolved import `piston::event_loop::*`. Could not find `event_loop` in `piston` [E0432]
src/lib.rs:80 pub use piston::event_loop::*;
                      ^~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:80:9: 80:31 help: run `rustc --explain E0432` to see a detailed explanation
src/lib.rs:79:9: 79:26 error: unresolved import `piston::input::*`. Could not find `input` in `piston` [E0432]
src/lib.rs:79 pub use piston::input::*;
                      ^~~~~~~~~~~~~~~~~
src/lib.rs:79:9: 79:26 help: run `rustc --explain E0432` to see a detailed explanation
src/lib.rs:198:13: 198:39 error: unresolved import `piston::event_loop::Events`. Could not find `event_loop` in `piston` [E0432]
src/lib.rs:198         use piston::event_loop::Events;
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:198:13: 198:39 help: run `rustc --explain E0432` to see a detailed explanation
src/lib.rs:199:45: 199:51 error: unresolved import `piston::window::Window`. Could not find `window` in `piston` [E0432]
src/lib.rs:199         use piston::window::{ OpenGLWindow, Window };
                                                           ^~~~~~
src/lib.rs:199:45: 199:51 help: run `rustc --explain E0432` to see a detailed explanation
src/lib.rs:199:31: 199:43 error: unresolved import `piston::window::OpenGLWindow`. Could not find `window` in `piston` [E0432]
src/lib.rs:199         use piston::window::{ OpenGLWindow, Window };
                                             ^~~~~~~~~~~~
src/lib.rs:199:31: 199:43 help: run `rustc --explain E0432` to see a detailed explanation
src/lib.rs:278:13: 278:39 error: unresolved import `piston::input::RenderEvent`. Could not find `input` in `piston` [E0432]
src/lib.rs:278         use piston::input::RenderEvent;
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:278:13: 278:39 help: run `rustc --explain E0432` to see a detailed explanation
src/lib.rs:256:13: 256:39 error: unresolved import `piston::input::RenderEvent`. Could not find `input` in `piston` [E0432]
src/lib.rs:256         use piston::input::RenderEvent;
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:256:13: 256:39 help: run `rustc --explain E0432` to see a detailed explanation
src/lib.rs:297:13: 297:30 error: unresolved import `piston::input::*`. Could not find `input` in `piston` [E0432]
src/lib.rs:297         use piston::input::*;
                           ^~~~~~~~~~~~~~~~~
src/lib.rs:297:13: 297:30 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to 9 previous errors
Could not compile `piston_window`.
```

**Comment by SonOfFlyingPig** [comment]
The problem also exists for 0.39.0, but not 0.38.0 .

**Comment by bvssvni** [comment]
This happens because of a breaking change in Rust with `pub extern crate`. We can break now or later, so we're breaking now. Use beta or nightly until next Rust release. See https://github.com/PistonDevelopers/piston/issues/1050

**Comment by SonOfFlyingPig** [comment]
Thanks for the info

**Comment by jstnlef** [comment]
I was seeing this too. Thanks.

**Comment by SonOfFlyingPig** [comment]
I can confirm that version 0.42.0 compiles with rust 1.8.
